title: '@slesaad: Jekyll Starter Kit'
tagline: 'A simple framework for starting your own Jekyll project'

author:
  name: 'Slesa Adhikari'

menu:
# Uncomment to activate the menu looping function in the header.html file under _includes
- {name: 'about', url: 'menu/about.md'}

social:
# Uncomment to activate the social media icon looping function in the footer.html file under _includes
#- {icon: 'github', link: 'https://www.github.com/lenpaul'}
